version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_4
  timestamp: 1494370500
layout:
  /navigation/:
    -
      - 'logo-9608 15'
      - 'menu-6409 65'
      - 'social-3171 20'
  /header/:
    -
      - owlcarousel-2455
  /intro/:
    -
      - imagegallerySZ-3581
  /features/: {  }
  /utility/:
    -
      - contenttabs-3854
  /above/:
    -
      - contentcubes-7850
  /testimonials/:
    -
      - testimonialSZ-3654
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-messages-1565
          -
            - system-content-7278
      -
        'sidebar 25': {  }
  /footer/:
    -
      - 'logo-1419 21'
      - 'copyright-9978 26'
      - 'horizontalmenu-7792 24'
      - 'totop-5265 29'
    -
      - socialfloatingSZ-3973
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
      class: g-flushed
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
      class: ''
      background: ''
      backgroundOverlay: 'rgba(0, 0, 0, 0)'
      backgroundAttachment: ''
      backgroundRepeat: ''
      backgroundPosition: ''
      backgroundSize: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
  social-3171:
    block:
      class: g-social-header
  owlcarousel-2455:
    title: 'Owl Carousel'
  imagegallerySZ-3581:
    title: 'Image Gallery'
  contenttabs-3854:
    title: 'Content Tabs'
  contentcubes-7850:
    title: 'Content Cubes'
  testimonialSZ-3654:
    title: Testimonials
  system-content-7278:
    attributes:
      enabled: 0
  logo-1419:
    title: 'Logo / Image'
    inherit:
      outline: 16
      include:
        - attributes
        - block
      particle: logo-6886
  copyright-9978:
    inherit:
      outline: 16
      include:
        - attributes
        - block
      particle: copyright-2297
  horizontalmenu-7792:
    title: 'Horizontal Menu'
    inherit:
      outline: 16
      include:
        - attributes
        - block
      particle: horizontalmenu-5057
  totop-5265:
    title: 'To Top'
    inherit:
      outline: 16
      include:
        - attributes
        - block
      particle: totop-1230
  socialfloatingSZ-3973:
    title: 'Social Floating'
    inherit:
      outline: 16
      include:
        - attributes
        - block
      particle: socialfloatingSZ-4980
