preset: preset2
base:
  dominant-color: '#4caf50'
accent:
  color-1: '#448aff'
  color-2: '#c8e6c9'
  color-3: '#388e3c'
zenith:
  link-color: '#4caf50'
navtop:
  link-color: '#4caf50'
navigation:
  background: '#4caf50'
header:
  link-color: '#4caf50'
intro:
  link-color: '#4caf50'
features:
  link-color: '#4caf50'
utility:
  link-color: '#4caf50'
above:
  link-color: '#4caf50'
testimonials:
  link-color: '#4caf50'
expanded:
  link-color: '#4caf50'
mainbottom:
  link-color: '#4caf50'
footertop:
  link-color: '#4caf50'
footer:
  link-color: '#c8e6c9'
footerbottom:
  link-color: '#4caf50'
nadir:
  link-color: '#4caf50'
offcanvas:
  background: '#4caf50'
